ETL SKILL

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
skill= pd.read_csv('skill_migration_public.csv')
skill.drop_duplicates(inplace=True)

In [ ]:
columns_to_check = skill.columns[12:]

columns_to_drop = []

for column in columns_to_check:
    if skill[column].isnull().all():
        columns_to_drop.append(column)

skill.drop(columns=columns_to_drop, inplace=True)

In [ ]:
column_rename_map = {}
for column in skill.columns:
    if column.startswith("net_per_10K_"):
        new_column_name = column.replace("net_per_10K_", "")
        column_rename_map[column] = new_column_name

skill.rename(columns=column_rename_map, inplace=True)

In [ ]:
columns_to_drop = ["wb_income", "wb_region", "skill_group_id"]
skill.drop(columns=columns_to_drop, inplace=True)

In [ ]:
skill_arg = skill[skill["country_name"] == "Argentina"]
skill_arg.reset_index(drop=True, inplace=True)

In [ ]:
skill_arg

,country_code,country_name,skill_group_category,skill_group_name,2015,2016,2017,2018,2019
0,ar,Argentina,Specialized Industry Skills,Sociology,-38.90,-126.02,-62.94,-71.28,-327.67
1,ar,Argentina,Business Skills,Affiliate Marketing,-134.97,-28.22,30.55,-83.54,-323.41
2,ar,Argentina,Business Skills,Sales Leads,-247.56,-157.47,-18.57,-117.29,-248.57
3,ar,Argentina,Specialized Industry Skills,Industrial Design,-84.95,-73.58,-32.87,-45.90,-245.16
4,ar,Argentina,Business Skills,Revenue Analysis,-87.48,-142.38,-115.12,-92.47,-233.48
...,...,...,...,...,...,...,...,...,...
166,ar,Argentina,Specialized Industry Skills,Electronic Control Systems,-53.34,64.95,154.56,222.89,23.41
167,ar,Argentina,Specialized Industry Skills,Utilities,-14.84,95.97,154.89,309.55,24.51
168,ar,Argentina,Specialized Industry Skills,Instrumentation,12.14,90.17,136.43,337.52,28.18
169,ar,Argentina,Specialized Industry Skills,Oil & Gas,8.50,112.19,173.10,417.52,87.37
170,ar,Argentina,Specialized Industry Skills,Drilling Engineering,33.35,191.54,321.82,607.12,108.72

In [ ]:
# Usar la funciÃ³n melt para convertir las columnas en filas
skill_arg_melted = skill_arg.melt(
    id_vars=['country_code', 'country_name', 'skill_group_category', 'skill_group_name'],
    value_vars=['2015', '2016', '2017', '2018', '2019'],
    var_name='year',
    value_name='value'
)

skill_arg_melted

,country_code,country_name,skill_group_category,skill_group_name,year,value
0,ar,Argentina,Specialized Industry Skills,Sociology,2015,-38.90
1,ar,Argentina,Business Skills,Affiliate Marketing,2015,-134.97
2,ar,Argentina,Business Skills,Sales Leads,2015,-247.56
3,ar,Argentina,Specialized Industry Skills,Industrial Design,2015,-84.95
4,ar,Argentina,Business Skills,Revenue Analysis,2015,-87.48
...,...,...,...,...,...,...
850,ar,Argentina,Specialized Industry Skills,Electronic Control Systems,2019,23.41
851,ar,Argentina,Specialized Industry Skills,Utilities,2019,24.51
852,ar,Argentina,Specialized Industry Skills,Instrumentation,2019,28.18
853,ar,Argentina,Specialized Industry Skills,Oil & Gas,2019,87.37
854,ar,Argentina,Specialized Industry Skills,Drilling Engineering,2019,108.72

In [ ]:
# Agrupar y sumar los valores por categorÃ­a de habilidad y aÃ±o
grouped_data = skill_arg_melted.groupby(['skill_group_category', 'year'])['value'].sum()

# Resetear el Ã­ndice de la agrupaciÃ³n y crear un nuevo DataFrame
new_df = grouped_data.reset_index()

In [ ]:
new_df

           skill_group_category  year    value
0               Business Skills  2015 -2416.93
1               Business Skills  2016  -646.51
2               Business Skills  2017  1004.40
3               Business Skills  2018  1252.79
4               Business Skills  2019 -4044.08
5        Disruptive Tech Skills  2015  -439.05
6        Disruptive Tech Skills  2016  -225.22
7        Disruptive Tech Skills  2017   214.02
8        Disruptive Tech Skills  2018   290.40
9        Disruptive Tech Skills  2019 -1025.57
10                  Soft Skills  2015  -697.14
11                  Soft Skills  2016  -213.93
12                  Soft Skills  2017   433.53
13                  Soft Skills  2018   639.92
14                  Soft Skills  2019 -1099.82
15  Specialized Industry Skills  2015 -3165.12
16  Specialized Industry Skills  2016 -2057.71
17  Specialized Industry Skills  2017  2361.33
18  Specialized Industry Skills  2018  4257.99
19  Specialized Industry Skills  2019 -8481.26
20                  Tech Skills  2015 -1127.53
21                  Tech Skills  2016  -929.18
22                  Tech Skills  2017    45.88
23                  Tech Skills  2018   202.26
24                  Tech Skills  2019 -2319.91

In [ ]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   skill_group_category  25 non-null     object
 1   year                  25 non-null     object
 2   value                 25 non-null     float64
dtypes: float64(1), object(2)
memory usage: 728.0+ bytes

In [ ]:
new_df['year'] = new_df['year'].astype(int)

In [ ]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   skill_group_category  25 non-null     object
 1   year                  25 non-null     int64
 2   value                 25 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 728.0+ bytes

In [ ]:
# Calcular el porcentaje de variaciÃ³n de la columna value respecto al aÃ±o anterior
new_df['Variation Percentage'] = ((new_df['value'] - new_df['value'].shift(1)) / abs(new_df['value'].shift(1)))

# Para el primer aÃ±o de cada categorÃ­a, el valor de Variation Percentage serÃ¡ NaN, lo reemplazamos con 0
new_df.loc[new_df.groupby('skill_group_category').head(1).index, 'Variation Percentage'] = 0

new_df

           skill_group_category  year    value  Variation Percentage
0               Business Skills  2015 -2416.93              0.000000
1               Business Skills  2016  -646.51              0.732508
2               Business Skills  2017  1004.40              2.553572
3               Business Skills  2018  1252.79              0.247302
4               Business Skills  2019 -4044.08             -4.228059
5        Disruptive Tech Skills  2015  -439.05              0.000000
6        Disruptive Tech Skills  2016  -225.22              0.487029
7        Disruptive Tech Skills  2017   214.02              1.950271
8        Disruptive Tech Skills  2018   290.40              0.356883
9        Disruptive Tech Skills  2019 -1025.57             -4.531577
10                  Soft Skills  2015  -697.14              0.000000
11                  Soft Skills  2016  -213.93              0.693132
12                  Soft Skills  2017   433.53              3.026504
13                  Soft Skills  2018   639.92              0.476069
14                  Soft Skills  2019 -1099.82             -2.718684
15  Specialized Industry Skills  2015 -3165.12              0.000000
16  Specialized Industry Skills  2016 -2057.71              0.349879
17  Specialized Industry Skills  2017  2361.33              2.147552
18  Specialized Industry Skills  2018  4257.99              0.803217
19  Specialized Industry Skills  2019 -8481.26             -2.991846
20                  Tech Skills  2015 -1127.53              0.000000
21                  Tech Skills  2016  -929.18              0.175915
22                  Tech Skills  2017    45.88              1.049377
23                  Tech Skills  2018   202.26              3.408457
24                  Tech Skills  2019 -2319.91            -12.469940

In [ ]:
# Crear una nueva columna con los valores del aÃ±o anterior multiplicados por 25%
new_df['prev_year_value'] = new_df.groupby('skill_group_category')['value'].shift(1)
new_df['value_increment'] = new_df['prev_year_value'] * 0.25

# Rellenar el valor del aÃ±o 2015 en la nueva columna
new_df.loc[new_df['year'] == 2015, 'value_increment'] = 0

# Hacer que los valores incrementados sean positivos
new_df['value_increment'] = new_df['value_increment'].abs()

# Filtrar solo los aÃ±os 2016 al 2019
filtered_df = new_df[new_df['year'].isin([2015, 2016, 2017, 2018, 2019])]

# Reiniciar el Ã­ndice
filtered_df = filtered_df.reset_index(drop=True)

# Imprimir el nuevo DataFrame
filtered_df

,skill_group_category,year,value,Variation Percentage,prev_year_value,value_increment
0,Business Skills,2015,-2416.93,0.000000,NaN,0.0000
1,Business Skills,2016,-646.51,0.732508,-2416.93,604.2325
2,Business Skills,2017,1004.40,2.553572,-646.51,161.6275
3,Business Skills,2018,1252.79,0.247302,1004.40,251.1000
4,Business Skills,2019,-4044.08,-4.228059,1252.79,313.1975
5,Disruptive Tech Skills,2015,-439.05,0.000000,NaN,0.0000
6,Disruptive Tech Skills,2016,-225.22,0.487029,-439.05,109.7625
7,Disruptive Tech Skills,2017,214.02,1.950271,-225.22,56.3050
8,Disruptive Tech Skills,2018,290.40,0.356883,214.02,53.5050
9,Disruptive Tech Skills,2019,-1025.57,-4.531577,290.40,72.6000
10,Soft Skills,2015,-697.14,0.000000,NaN,0.0000
11,Soft Skills,2016,-213.93,0.693132,-697.14,174.2850
12,Soft Skills,2017,433.53,3.026504,-213.93,53.4825
13,Soft Skills,2018,639.92,0.476069,433.53,108.3825
14,Soft Skills,2019,-1099.82,-2.718684,639.92,159.9800
15,Specialized Industry Skills,2015,-3165.12,0.000000,NaN,0.0000
16,Specialized Industry Skills,2016,-2057.71,0.349879,-3165.12,791.2800
17,Specialized Industry Skills,2017,2361.33,2.147552,-2057.71,514.4275
18,Specialized Industry Skills,2018,4257.99,0.803217,2361.33,590.3325
19,Specialized Industry Skills,2019,-8481.26,-2.991846,4257.99,1064.4975
20,Tech Skills,2015,-1127.53,0.000000,NaN,0.0000
21,Tech Skills,2016,-929.18,0.175915,-1127.53,281.8825
22,Tech Skills,2017,45.88,1.049377,-929.18,232.2950
23,Tech Skills,2018,202.26,3.408457,45.88,11.4700
24,Tech Skills,2019,-2319.91,-12.469940,202.26,50.5650

skill_arg_melted

In [ ]:
# Guardar el dataframe como archivo CSV
filtered_df.to_csv('skill_Arg.csv', index=False)

In [ ]:
skill_arg_melted.to_csv('skill_Arg_All.csv', index=False)