In [1]:
import pandas as pd

In [ ]:
df = pd.read_excel('NetMigration.xlsx')

In [ ]:
df.head(10)

                  Country Name Country Code  Year  Migración Neta
0                        Aruba          ABW  1960             0.0
1  Africa Eastern and Southern          AFE  1960        -90849.0
2                  Afghanistan          AFG  1960          2606.0
3   Africa Western and Central          AFW  1960          -847.0
4                       Angola          AGO  1960        -43749.0
5                      Albania          ALB  1960         15540.0
6                      Andorra          AND  1960           642.0
7                   Arab World          ARB  1960       -111478.0
8         United Arab Emirates          ARE  1960          3916.0
9                    Argentina          ARG  1960         20399.0

In [ ]:
# Crear un nuevo DataFrame solo para Argentina
df_argentina = df.loc[df['Country Name'] == 'Argentina']

# Mostrar el nuevo DataFrame
df_argentina

      Country Name Country Code  Year  Migración Neta
9        Argentina          ARG  1960         20399.0
275      Argentina          ARG  1961         29321.0
541      Argentina          ARG  1962         29386.0
807      Argentina          ARG  1963         30637.0
1073     Argentina          ARG  1964         32322.0
...            ...          ...   ...             ...
15437    Argentina          ARG  2018          4690.0
15703    Argentina          ARG  2019          4478.0
15969    Argentina          ARG  2020          2344.0
16235    Argentina          ARG  2021          2344.0
16501    Argentina          ARG  2022             NaN

[63 rows x 4 columns]

In [ ]:
# Crear un nuevo DataFrame solo para Argentina y reiniciar el índice
df_argentina = df[df['Country Name'] == 'Argentina'].reset_index(drop=True)

# Mostrar el nuevo DataFrame
df_argentina.head(10)

  Country Name Country Code  Year  Migración Neta
0    Argentina          ARG  1960         20399.0
1    Argentina          ARG  1961         29321.0
2    Argentina          ARG  1962         29386.0
3    Argentina          ARG  1963         30637.0
4    Argentina          ARG  1964         32322.0
5    Argentina          ARG  1965         33973.0
6    Argentina          ARG  1966         35529.0
7    Argentina          ARG  1967         37727.0
8    Argentina          ARG  1968         39985.0
9    Argentina          ARG  1969         40436.0

In [ ]:
# Calcular el porcentaje de variación en la columna "Migración Neta"
df_argentina['Variación %'] = df_argentina['Migración Neta'].pct_change()

# Mostrar el DataFrame resultante
df_argentina

   Country Name Country Code  Year  Migración Neta  Variación %
0     Argentina          ARG  1960         20399.0          NaN
1     Argentina          ARG  1961         29321.0     0.437374
2     Argentina          ARG  1962         29386.0     0.002217
3     Argentina          ARG  1963         30637.0     0.042571
4     Argentina          ARG  1964         32322.0     0.054999
..          ...          ...   ...             ...          ...
58    Argentina          ARG  2018          4690.0    -0.047909
59    Argentina          ARG  2019          4478.0    -0.045203
60    Argentina          ARG  2020          2344.0    -0.476552
61    Argentina          ARG  2021          2344.0     0.000000
62    Argentina          ARG  2022             NaN     0.000000

[63 rows x 5 columns]

In [ ]:
# Calcular el incremento del 1% respecto del año anterior
df_argentina['Migración Neta Incrementado'] = df_argentina['Migración Neta'].shift(1) * 1.01

# Mostrar el DataFrame resultante
df_argentina

,Country Name,Country Code,Year,Migración Neta,Variación %,Migración Neta Incrementado
0,Argentina,ARG,1960,20399.0,NaN,NaN
1,Argentina,ARG,1961,29321.0,0.437374,20602.99
2,Argentina,ARG,1962,29386.0,0.002217,29614.21
3,Argentina,ARG,1963,30637.0,0.042571,29679.86
4,Argentina,ARG,1964,32322.0,0.054999,30943.37
...,...,...,...,...,...,...
58,Argentina,ARG,2018,4690.0,-0.047909,4975.26
59,Argentina,ARG,2019,4478.0,-0.045203,4736.90
60,Argentina,ARG,2020,2344.0,-0.476552,4522.78
61,Argentina,ARG,2021,2344.0,0.000000,2367.44
62,Argentina,ARG,2022,NaN,0.000000,2367.44

In [ ]:
# Eliminar la fila correspondiente a 2022 en la columna "Year"
year_to_drop = 2022
df_argentina = df_argentina[df_argentina['Year'] != year_to_drop]

In [ ]:
df_argentina

,Country Name,Country Code,Year,Migración Neta,Variación %,Migración Neta Incrementado
0,Argentina,ARG,1960,20399.0,NaN,NaN
1,Argentina,ARG,1961,29321.0,0.437374,20602.99
2,Argentina,ARG,1962,29386.0,0.002217,29614.21
3,Argentina,ARG,1963,30637.0,0.042571,29679.86
4,Argentina,ARG,1964,32322.0,0.054999,30943.37
...,...,...,...,...,...,...
57,Argentina,ARG,2017,4926.0,-0.055417,5267.15
58,Argentina,ARG,2018,4690.0,-0.047909,4975.26
59,Argentina,ARG,2019,4478.0,-0.045203,4736.90
60,Argentina,ARG,2020,2344.0,-0.476552,4522.78
61,Argentina,ARG,2021,2344.0,0.000000,2367.44

In [ ]:
# Guardar el dataframe como archivo CSV
df_argentina.to_csv('NetMigrationArg.csv', index=False)