SISTEMA RECOMENDACION MIGRACION NETA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
Mig_neta= pd.read_csv('Migracion Neta.csv')

In [7]:
Mig_neta.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,Unnamed: 67
0,Aruba,ABW,Migración neta,SM.POP.NETM,0.0,-569.0,-609.0,-646.0,-684.0,-726.0,...,88.0,177.0,170.0,218.0,367.0,412.0,0.0,501.0,NaN,NaN
1,NaN,AFE,Migración neta,SM.POP.NETM,-90849.0,-1348.0,-24259.0,-16266.0,37452.0,11041.0,...,-199608.0,394925.0,-864708.0,-343075.0,-366105.0,-187410.0,-48955.0,-179444.0,NaN,NaN
2,Afganistán,AFG,Migración neta,SM.POP.NETM,2606.0,6109.0,7016.0,6681.0,7079.0,10695.0,...,255611.0,-281739.0,-90238.0,-47090.0,-47205.0,-8082.0,166821.0,-183672.0,NaN,NaN
3,NaN,AFW,Migración neta,SM.POP.NETM,-847.0,-41547.0,-36399.0,-37435.0,-45534.0,-15985.0,...,-280418.0,-360393.0,-167286.0,-200823.0,-255888.0,-328552.0,-99761.0,-264802.0,NaN,NaN
4,Angola,AGO,Migración neta,SM.POP.NETM,-43749.0,-49186.0,-54566.0,-59777.0,-71948.0,-87288.0,...,84532.0,74170.0,91623.0,77733.0,61632.0,58986.0,7557.0,29089.0,NaN,NaN
5,Albania,ALB,Migración neta,SM.POP.NETM,15540.0,15424.0,15288.0,15007.0,14612.0,14209.0,...,-14265.0,-12240.0,-10887.0,-9768.0,-9106.0,-8889.0,-9117.0,-10612.0,NaN,NaN
6,Andorra,AND,Migración neta,SM.POP.NETM,642.0,653.0,664.0,670.0,672.0,669.0,...,-84.0,-232.0,1303.0,887.0,1184.0,1238.0,1474.0,1377.0,NaN,NaN
7,El mundo árabe,ARB,Migración neta,SM.POP.NETM,-111478.0,-176004.0,-144522.0,-184289.0,-173533.0,-186104.0,...,-184490.0,-194516.0,3140.0,13305.0,511128.0,139844.0,-1585167.0,-458710.0,NaN,NaN
8,Emiratos Árabes Unidos,ARE,Migración neta,SM.POP.NETM,3916.0,4081.0,4108.0,4037.0,3922.0,3866.0,...,-14954.0,-14154.0,-13520.0,-12895.0,-8582.0,-4466.0,-2762.0,-2762.0,NaN,NaN
9,Argentina,ARG,Migración neta,SM.POP.NETM,20399.0,29321.0,29386.0,30637.0,32322.0,33973.0,...,5801.0,5522.0,5215.0,4926.0,4690.0,4478.0,2344.0,2344.0,NaN,NaN

In [8]:
Mig_neta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 68 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    264 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            265 non-null    float64
 5   1961            265 non-null    float64
 6   1962            265 non-null    float64
 7   1963            265 non-null    float64
 8   1964            265 non-null    float64
 9   1965            265 non-null    float64
 10  1966            265 non-null    float64
 11  1967            265 non-null    float64
 12  1968            265 non-null    float64
 13  1969            265 non-null    float64
 14  1970            265 non-null    float64
 15  1971            265 non-null    float64
 16  1972            265 non-null    float64
 17  1973            265 non-null    float64
 18  1974            265 non-null    float64
 19  1975            265 non-null    float64
 20  1976            265 non-null    float64
 21  1977            265 non-null    float64
 22  1978            265 non-null    float64
 23  1979            265 non-null    float64
 24  1980            265 non-null    float64
 25  1981            265 non-null    float64
 26  1982            265 non-null    float64
 27  1983            265 non-null    float64
 28  1984            265 non-null    float64
 29  1985            265 non-null    float64
 30  1986            265 non-null    float64
 31  1987            265 non-null    float64
 32  1988            265 non-null    float64
 33  1989            265 non-null    float64
 34  1990            265 non-null    float64
 35  1991            265 non-null    float64
 36  1992            265 non-null    float64
 37  1993            265 non-null    float64
 38  1994            265 non-null    float64
 39  1995            265 non-null    float64
 40  1996            265 non-null    float64
 41  1997            265 non-null    float64
 42  1998            265 non-null    float64
 43  1999            265 non-null    float64
 44  2000            265 non-null    float64
 45  2001            265 non-null    float64
 46  2002            265 non-null    float64
 47  2003            265 non-null    float64
 48  2004            265 non-null    float64
 49  2005            265 non-null    float64
 50  2006            265 non-null    float64
 51  2007            265 non-null    float64
 52  2008            265 non-null    float64
 53  2009            265 non-null    float64
 54  2010            265 non-null    float64
 55  2011            265 non-null    float64
 56  2012            265 non-null    float64
 57  2013            265 non-null    float64
 58  2014            265 non-null    float64
 59  2015            265 non-null    float64
 60  2016            265 non-null    float64
 61  2017            265 non-null    float64
 62  2018            265 non-null    float64
 63  2019            265 non-null    float64
 64  2020            265 non-null    float64
 65  2021            265 non-null    float64
 66  2022            0 non-null      float64
 67  Unnamed: 67     0 non-null      float64
dtypes: float64(64), object(4)
memory usage: 141.4+ KB

In [9]:
# Lista de columnas a eliminar
columns_to_drop = ['Indicator Name', 'Indicator Code']

# Eliminar las columnas
Mig_neta = Mig_neta.drop(columns=columns_to_drop)

In [10]:
print(Mig_neta['2021'].isnull().sum())

1

In [11]:
# Eliminar filas con valores nulos en la columna '2021'
Mig_neta = Mig_neta.dropna(subset=['2021'])

In [12]:
print(Mig_neta['2021'].isnull().sum())

0

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.impute import SimpleImputer


# Seleccionar las columnas de años desde 1960 hasta 2020 como características
features = Mig_neta.columns[3:-1]

# Separar los datos en características (X) y variable objetivo (y)
X = Mig_neta[features]
y = Mig_neta['2021']  # Columna correspondiente a 2021

# Manejar los valores faltantes en X
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X_imputed, y, test_size=0.2, random_state=42)

# Crear el modelo de regresión lineal
model = LinearRegression()

# Entrenar el modelo
model.fit(X_train, y_train)

# Realizar predicciones en el conjunto de prueba
y_pred = model.predict(X_test)

# Evaluar el rendimiento del modelo
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse:.2f}')
print(f'R-squared: {r2:.2f}')

Mean Squared Error: 0.00
R-squared: 1.00

LinearRegression

In [14]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.impute import SimpleImputer


# Seleccionar las columnas de años desde 1960 hasta 2020 como características
features = Mig_neta.columns[3:-1]

# Separar los datos en características (X) y variable objetivo (y)
X = Mig_neta[features]
y = Mig_neta['2021']  # Columna correspondiente a 2021

# Manejar los valores faltantes en X
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

# Crear el modelo de regresión lineal
model = LinearRegression()

# Entrenar el modelo
model.fit(X_imputed, y)

# Predecir los valores de migración neta para el año 2022
X_pred_2022 = X_imputed  # Usar todos los datos imputados para predecir 2022
y_pred_2022 = model.predict(X_pred_2022)

# Crear un DataFrame con las predicciones para el año 2022
predictions_2022 = pd.DataFrame({
    'Country Name': Mig_neta['Country Name'],
    'Country Code': Mig_neta['Country Code'],
    '2022': y_pred_2022
})

# Imprimir el DataFrame con las predicciones para el año 2022
predictions_2022. head(10)

             Country Name Country Code      2022
0                   Aruba          ABW     501.0
1                     NaN          AFE -179444.0
2              Afganistán          AFG -183672.0
3                     NaN          AFW -264802.0
4                  Angola          AGO   29089.0
5                 Albania          ALB  -10612.0
6                 Andorra          AND    1377.0
7          El mundo árabe          ARB -458710.0
8  Emiratos Árabes Unidos          ARE   -2762.0
9               Argentina          ARG    2344.0

Regresión Ridge

In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.impute import SimpleImputer



# Seleccionar las columnas de años desde 1960 hasta 2020 como características
features = Mig_neta.columns[3:-1]

# Separar los datos en características (X) y variable objetivo (y)
X = Mig_neta[features]
y = Mig_neta['2021']  # Columna correspondiente a 2021

# Manejar los valores faltantes en X
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X_imputed, y, test_size=0.2, random_state=42)

# Crear el modelo de regresión Ridge
ridge_model = Ridge(alpha=1.0)  #  ajustar el valor de alpha según sea necesario

# Entrenar el modelo
ridge_model.fit(X_train, y_train)

# Predecir los valores de migración neta para el año 2022
X_pred_2022 = X_imputed  # Usar todos los datos imputados para predecir 2022
y_pred_2022 = ridge_model.predict(X_pred_2022)

# Calcular las métricas de rendimiento
mse = mean_squared_error(y_test, ridge_model.predict(X_test))
r2 = r2_score(y_test, ridge_model.predict(X_test))

# Crear un DataFrame con las predicciones para el año 2022
predictions_2022 = pd.DataFrame({
    'Country Name': Mig_neta['Country Name'],
    'Country Code': Mig_neta['Country Code'],
    '2022': y_pred_2022
})


predictions_2022

# Imprimir las métricas de rendimiento
print(f'Mean Squared Error: {mse:.2f}')
print(f'R-squared: {r2:.2f}')

Mean Squared Error: 0.00
R-squared: 1.00

In [16]:
# Imprimir el DataFrame con las predicciones para el año 2022
predictions_2022

        Country Name Country Code           2022
0              Aruba          ABW     501.000000
1                NaN          AFE -179444.000000
2         Afganistán          AFG -183672.000000
3                NaN          AFW -264802.000000
4             Angola          AGO   29089.000001
..               ...          ...            ...
261           Kosovo          XKX  -15050.000000
262  Yemen, Rep. del          YEM -101467.999998
263        Sudáfrica          ZAF   10934.000000
264           Zambia          ZMB    9015.000001
265         Zimbabwe          ZWE  -25005.000000

[265 rows x 3 columns]

RandomForestRegressor

In [17]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.impute import SimpleImputer



# Seleccionar las columnas de años desde 1960 hasta 2020 como características
features = Mig_neta.columns[3:-1]

# Separar los datos en características (X) y variable objetivo (y)
X = Mig_neta[features]
y = Mig_neta['2021']  # Columna correspondiente a 2021

# Manejar los valores faltantes en X
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X_imputed, y, test_size=0.2, random_state=42)

# Crear el modelo de Random Forest Regressor
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)  # ajustar los hiperparámetros según sea necesario

# Entrenar el modelo
rf_model.fit(X_train, y_train)

# Predecir los valores de migración neta para el año 2022
X_pred_2022 = X_imputed  # Usar todos los datos imputados para predecir 2022
y_pred_2022 = rf_model.predict(X_pred_2022)

# Calcular las métricas de rendimiento
mse = mean_squared_error(y_test, rf_model.predict(X_test))
r2 = r2_score(y_test, rf_model.predict(X_test))

# Crear un DataFrame con las predicciones para el año 2022
predictions_2022 = pd.DataFrame({
    'Country Name': Mig_neta['Country Name'],
    'Country Code': Mig_neta['Country Code'],
    '2022': y_pred_2022
})


# Imprimir las métricas de rendimiento
print(f'Mean Squared Error: {mse:.2f}')
print(f'R-squared: {r2:.2f}')

Mean Squared Error: 6291900483.20
R-squared: 0.93

In [18]:
# Imprimir el DataFrame con las predicciones para el año 2022
predictions_2022.head(10)

             Country Name Country Code       2022
0                   Aruba          ABW     473.90
1                     NaN          AFE -176546.02
2              Afganistán          AFG -183108.93
3                     NaN          AFW -263229.49
4                  Angola          AGO   27038.68
5                 Albania          ALB  -10388.07
6                 Andorra          AND    1248.97
7          El mundo árabe          ARB -401757.04
8  Emiratos Árabes Unidos          ARE   -2901.81
9               Argentina          ARG    2550.80

K vecinos

In [27]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.impute import SimpleImputer



# Seleccionar las columnas de años desde 1960 hasta 2020 como características
features = Mig_neta.columns[3:-1]

# Separar los datos en características (X) y variable objetivo (y)
X = Mig_neta[features]
y = Mig_neta['2021']  # Columna correspondiente a 2021

# Manejar los valores faltantes en X
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X_imputed, y, test_size=0.2, random_state=42)

# Crear el modelo de KNeighborsRegressor
k_neighbors_model = KNeighborsRegressor(n_neighbors=5)  #  ajustar el número de vecinos según sea necesario

# Entrenar el modelo
k_neighbors_model.fit(X_train, y_train)

# Predecir los valores de migración neta para el año 2022
X_pred_2022 = X_imputed  # Usar todos los datos imputados para predecir 2022
y_pred_2022 = k_neighbors_model.predict(X_pred_2022)

# Calcular las métricas de rendimiento
mse = mean_squared_error(y_test, k_neighbors_model.predict(X_test))
r2 = r2_score(y_test, k_neighbors_model.predict(X_test))

# Crear un DataFrame con las predicciones para el año 2022
predictions_2022 = pd.DataFrame({
    'Country Name': Mig_neta['Country Name'],
    'Country Code': Mig_neta['Country Code'],
    '2022': y_pred_2022
})



# Imprimir las métricas de rendimiento
print(f'Mean Squared Error: {mse:.2f}')
print(f'R-squared: {r2:.2f}')

Mean Squared Error: 5692848923.78
R-squared: 0.94

In [25]:
predictions_2022

        Country Name Country Code           2022
0              Aruba          ABW     209.666667
1                NaN          AFE -356027.333333
2         Afganistán          AFG  -72483.000000
3                NaN          AFW -134481.333333
4             Angola          AGO   42835.666667
..               ...          ...            ...
261           Kosovo          XKX  -11912.333333
262  Yemen, Rep. del          YEM  -46990.000000
263        Sudáfrica          ZAF    9824.333333
264           Zambia          ZMB   -2190.000000
265         Zimbabwe          ZWE  -22208.666667

[265 rows x 3 columns]